project_id = "vshwgudoizqmbjsdecac"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = "./supabase/templates/email_change.html"

[auth.hook.send_email]
enabled = true
uri = "https://vshwgudoizqmbjsdecac.supabase.co/functions/v1/send-email"
secrets = "SEND_EMAIL_HOOK_SECRET"
